# Generated by Django 5.0.6 on 2024-08-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PickDropApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration_model',
            old_name='phone_number',
            new_name='mobile',
        ),
    ]
