# Generated by Django 5.0.6 on 2024-08-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickDropApp', '0003_professional_registration_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_registration_model',
            name='load_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
