# Generated by Django 5.0.6 on 2024-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickDropApp', '0004_professional_registration_model_load_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_dashboard_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
    ]
