# Generated by Django 5.0.6 on 2024-08-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickDropApp', '0005_user_dashboard_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_dashboard_model',
            name='user_email',
            field=models.EmailField(default='sunny@gmail.com', max_length=254),
        ),
    ]
