# Generated by Django 5.0.6 on 2024-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickDropApp', '0006_user_dashboard_model_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_dashboard_model',
            name='dropoff_coords',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_dashboard_model',
            name='pickup_coords',
            field=models.FloatField(default=0),
        ),
    ]
