# Generated by Django 5.0.6 on 2024-08-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickDropApp', '0008_professional_dashboard_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_dashboard_model',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional_dashboard_model',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
