# Generated by Django 5.0.6 on 2024-09-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickDropApp', '0009_professional_dashboard_model_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_dashboard_model',
            name='user_mobile',
            field=models.IntegerField(default=9876351239),
        ),
    ]
