# Generated by Django 5.0.6 on 2024-09-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickDropApp', '0010_user_dashboard_model_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_dashboard_model',
            name='user_mobile',
            field=models.IntegerField(default='9876351239'),
        ),
    ]
